#!/bin/bash

MY_REPO_GITHUB_URL="https://github.com/KaiserErwin"

TIME_ZONE="America/Montevideo"
USERNAME="user"
EFI="/boot/efi"
BOOT_NAME="Arch Linux"
LANG="es_UY"
KEYMAP="en"
HOSTNAME="ArchLinux"
INSPIRON=false
MY_CONFIG=false
SHELL="bash"

# Colors
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
NORMAL="\033[0m"
BLUE="\033[0;34m"

# TODO: Cambiar mensages de error o panic
warn() {
  echo -e "${YELLOW}-> Warning:${NORMAL} $1" >&2
}

error() {
  echo -e "${RED}==> Error:${NORMAL} $1" >&2
}

panic() {
  echo -e "${RED}==> Panic:${NORMAL} $1" >&2
  exit 1
}

message() {
  echo -e "${BLUE}==> Info:${NORMAL} $1"
}

question() {
  echo -e "${GREEN}==> Questions:${NORMAL} $1"
}

# Functions
program_exists() {
    command -v $1 &> /dev/null
}

command_success() {
  if [[ $1 == 1 ]]; then
    error $2

    question "Do you want to continue?"
    read -p "-> Yes/No: " OPTION

    if [[ ${OPTION,,} == "yes" ]] || [[ $OPTION == "" ]]; then
        warn "Continuing . . . $3"
        return 0
    fi
    panic $2
  fi
}

get_aur() {
  git clone https://aur.archlinux.org/$1.git $MOUNT/opt/$1
  cd /opt/$1
  makepkg -si
}

test_conexion(){
  echo -e "GET http://archlinux.org HTTP/1.0\n\n" | nc archlinux.org 80 > /dev/null 2>&1
  [[ $? == 1 ]] && panic "There is no Internet conection . . . Can't continue" || message "Internet connection"
}

is_mounted() { 
  findmnt "$1" >/dev/null 
}

config_to_dell_instpiron() {
  echo "options snd-intel-dspcfg dsp_driver=1 \
        options snd-hda-intel dmic_detect=0 \
        # Add delayed register for HyperX Cloud Flight S Headset \
        options snd-usb-audio delayed_register=095116ea:02 \
        options snd-usb-audio quirk_alias=095116ea:095116d8 delayed_register=095116ea:02" >> /etc/modprobe.d/alas.conf
  command_success $? "" ""

  sed -i -e 's/MODULES=()/MODULES=( vmd )' /etc/mkinitcpio.conf
  command_success $? "" ""

  mkinitcpio -P
  command_success $? "" ""
}

create_user(){
  question "Create a user?"
  read -p "-> Yes/No: " OPTION

  if [[ "${OPTION,,}" == "yes" ]] || [[ $OPTION == "" ]]; then
    read -p "--> username: " USERNAME
    useradd -m -g users -G audio,lp,optical,storage,video,wheel,power -s /bin/bash $USERNAME
    return `command_success $? "The new user could not be created" "Not create new user"`

    passwd $USERNAME
  fi
}

get_my_config() {
  PACKAGES_TO_INSTALL="$SHELL neovim git bspwm sxhkd rofi nodejs npm python python-pip ruby rubygems xsel fzf ripgrep fd prettier pacman-contrib brightnessctl pamixer upower"
  AUR_PACKAGES_TO_INSTALL="lightdm-webkit2-theme-glorious stacer brave-bin brave-beta-bin nerd-fonts-ubuntu-mono nerd-fonts-jetbrains-mono nerd-fonts-liberation-mono eslint standard cmake-language-server vscode-json-languageserver"   

  pacman -Sy --noconfirm $PACKAGES_TO_INSTALL
  command_success $? "" ""
  sed -i 's/^\(#?greeter\)-session\s*=\s*\(.*\)/greeter-session = lightdm-webkit2-greeter #\1/ #\2g' /etc/lightdm/lightdm.conf
  sed -i 's/^webkit_theme\s*=\s*\(.*\)/webkit_theme = glorious #\1/g' /etc/lightdm/lightdm-webkit2-greeter.conf
  sed -i 's/^debug_mode\s*=\s*\(.*\)/debug_mode = true #\1/g' /etc/lightdm/lightdm-webkit2-greeter.conf

  get_aur "paru"

  paru --noconfirm $AUR_PACKAGES_TO_INSTALL
  command_success $? "" ""
 
  pip install neovim
  gem install neovim
  npm i -g neovim

  chsh -s /bin/$SHELL $USERNAME

  git clone "$MY_GITHUB/dotfiles.git" /home/$USERNAME/dotfiles
  cd /home/$USERNAME/

  message "Copying files in HOME from $USERNAME"
  cp -r dotfiles/.config/*/ "/home/$USERNAME"
  cp -r dotfiles/.zshrc "/home/$USERNAME"
  cp -r dotfiles/.xprofile "/home/$USERNAME"
  cp -r dotfiles/zsh_plugins/* /usr/share/
  cp dotfiles/.local/bin/percentage /home/$USERNAME/.local/bin/
  cp dotfiles/.local/bin/battery /home/$USERNAME/.local/bin/
  cp dotfiles/.local/bin/brightness /home/$USERNAME/.local/bin/
  cp dotfiles/.local/bin/volume /home/$USERNAME/.local/bin/

  message "Moved the dotfiles directory in Home with the name .dotfiles"
  mv dotfiles /home/$USERNAME/.dotfiles

  echo "[D-BUS Service] \
        Name=org.freedesktop.Notifications \
        Exec=/usr/lib/notification-daemon-1.0/notification-daemon" >> /usr/share/dbus-1/services/org.freedesktop.Notifications.service
}

grub() {
  message "Grub install"
  grub-install --efi-directory="$MOUNT/$EFI" --bootloader-id=$BOOT_NAME --target=x86_64-efi
  command_success $? "The grub could not be installed" "Grub not installed"

  message "Grub config"
  echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
  if [[ $? == 1 ]]; then
    warn "Could not add OS-prober option"
  fi

  grub-mkconfig -o /boot/grub/grub.cfg
  command_success $? "Could not configure grub" "Grub not config"
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  KEY="$1"

  case $KEY in
    -s|--shell)
        SHELL="$2"
        shift
        shift
      ;;
    -t|--time)
      TIME_ZONE="$2"
      shift
      shift
    ;;
    -l|--lang)
      LANG="$2"
      shift
      shift
      shift
    ;;
    -k|--keymap)
      KEYMAP="$2"
      shift
      shift
    ;;
    -H|--hostname)
      HOSTNAME="$2"
      shift
      shift
    ;;
    -e|--efi)
      is_mounted "$2" && EFI="$2" || panic "Device EFI is not mounted"
      shift
      shift
    ;;
    --inspiron)
      INSPIRON=true
      shift
      shift
    ;;
    -b|--boot-name)
      BOOT_NAME="$2"
      shift
      shift
    ;;
    -c|--my-config)
      MY_CONFIG=true
      shift
      shift
    ;;
    -u|--username)
      USERNAME="$2"
      shift
      shift
    ;;
    *)
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

test_conexion

message "Set zonetime"
ln -sf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime
command_success $? "" ""

hwclock --systohc
command_success $? "" ""

message "Set lang sistem"
echo "LANG="$LANG.UTF-8"" > /etc/locale.conf
command_success $? "" ""

echo "$LANG.UTF-8 UTF-8" > /etc/locale.gen
command_success $? "" ""

message "Set Keymap"
echo "KEYMAP="$KEYMAP"" > /etc/vconsole.conf
command_success $? "" ""

message "Set hostname"
echo $HOSTNAME > /etc/hostname
command_success $? "" ""

fc-list

if [[ $INSPIRON == true ]]; then
 config_to_dell_instpiron
fi

create_user

if [[ $MY_CONFIG == true ]]; then
  get_my_config
fi

grub
